### ISSUE TITLE
[Relational] Projects seem to have net_estimated_bmr_units filled out when they shouldn't?

### ISSUE THREAD

**Issue by ilakyapal** [sfcpc/housing-dashboard#132]
It seems like we have "TBD" units showing up even for projects whose latest status is beyond under entitlement review, which seems incorrect?

**Comment by rajpara11** [comment]
We talked about this offline with @ilakyapal and @thelee but wanted to just update this issue for posterity. Right now the only trustable source we have for bmr units is mohcd. If we don't have mohcd data for a project, we will rely on the planning affordable_units field if it exists and is > 0.

However, if both of those things aren't true, then we can have both planning and pts statuses that have estimated affordable unit counts associated with them, so basically this is WAI for now.

**Comment by rajpara11** [comment]
Brought up as comment in the UX mocks at https://docs.google.com/presentation/d/1eIDfcBjZYtNo5LbKu6OvtuwP8v3rTfu9XiIrz2qL0kw/edit?disco=AAAAGQcIrus

**Comment by rajpara11** [comment]
Closing this out now since we know it's WAI and we should file another issue if we want to fix this specifically
