### ISSUE TITLE
Add a script that spits out a "log" file with information regarding uncertain project linkages

### ISSUE THREAD

**Issue by ilakyapal** [sfcpc/housing-dashboard#55]
As discussed in the tech meeting today, it could be useful if in create_uuid_map we have some logic that tries to associate projects across departments with some (fancier) heuristics as outlined in Raj's doc and spits out these "low confidence" linkages in some log file so that someone like Svetha might be able to use for her reports/do manual corrections .

**Comment by sbuss** [comment]
This was completed in #85
