### ISSUE TITLE
Add 'Inclusionary Portfolio' to schemaless

### ISSUE THREAD

**Issue by rajpara11** [sfcpc/housing-dashboard#58]
https://data.sfgov.org/Housing-and-Buildings/Residential-Projects-With-Inclusionary-Requirement/nj3x-rw36

This is combined with the affordable rental portfolio and affordable housing pipeline to give the most holistic view of MOHCD projects

**Comment by ilakyapal** [comment]
Note, this is different than the Affordable Rental Portfolio. We can join on planning case number.
