### ISSUE TITLE
Generate entire status history for a project

### ISSUE THREAD

**Issue by thelee** [sfcpc/housing-dashboard#61]
Need to ingest and output the status history for a project. Table currently not populated at all.

**Comment by thelee** [comment]
assigning to you raj since you mentioned you'd be willing to pick up something here

**Comment by thelee** [comment]
if you also have thoughts on improving the structure viz https://github.com/sfcpc/housing-dashboard/issues/64 that would also be great

**Comment by rajpara11** [comment]
Closed by https://github.com/sfcpc/housing-dashboard/pull/113
