### ISSUE TITLE
Ignore projects that have no root that is from PPTS

### ISSUE THREAD

**Issue by thelee** [sfcpc/housing-dashboard#82]
PTS have plenty of orphan records that could be leading to double-count so far. Same with MOHCD

**Comment by rajpara11** [comment]
Question here @thelee, I think you landed a change to protect against this by making sure PPTS was the source data for the root, but do we need to also make sure that the parent has a record type of PRJ?

**Comment by thelee** [comment]
sorry i missed this update.

i was not filtering out PRJs but records would not have been emitted if there were 0 net units. i'm doing a test run with PRJ-specific root filtering in place to see how it affects the tables. From a logical perspective, it seems to make sense that we should limit to PRJ roots, but i'm not confident on that.

**Comment by thelee** [comment]
ok, after running the numbers, i **don't** think we should filter to just PRJ roots. Some of the entries we lose are PRLs that have explicitly set 0 net units (either via planning or dbi permit records) so aren't a big win, but we also get a periodic PRL with a net gain of units, and so far I've found one mohcd project that is rooted back to an ENF ppts record (!!)

**Comment by thelee** [comment]
i'm marking this as closed for now
