### ISSUE TITLE
[Relational] Properly sum up net unit counts across all linked (unique?) PTS records

### ISSUE THREAD

**Issue by thelee** [sfcpc/housing-dashboard#96]
Currently the relational table logic is just to pick one, which works well enough when we only have one permit linked, or when there are dupes that might just be an artifact of a join.

However, this already understates the true unit count, and there's a near future where there's multiple permits for a project, and the logic needs to be able to sum across all of them (possibly ignoring dupes, depending on what we determine).

We might also have a warning to log if totaled numbers from PTS differ from PPTS by a significant margin.

**Comment by thelee** [comment]
raj: also assigning this to you because you mentioned you were going to look at doing something with alton's logic

**Comment by rajpara11** [comment]
sg, [filed issue 95](https://github.com/sfcpc/housing-dashboard/issues/95) as a place for me to dump some thoughts on the actual grouping part, will leave this issue as 'handling the relational side'
